schema_version: 1

context:
  name: opentelemetry-instrumentation-openai
  version: "0.62.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/opentelemetry_instrumentation_openai-${{ version }}.tar.gz
  sha256: a2c03cf4b8c18ed5e53d4a59b3299df39858640e41b91379ca72153a3f85a716

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0
    - tiktoken >=0.6.0,<1
    - typing-extensions

tests:
  - requirements:
      run:
        - python ${{ python_min }}.*
        - openai
        - pip
    script:
      - python -c "import opentelemetry.instrumentation.openai"
      - pip check

about:
  summary: OpenTelemetry OpenAI instrumentation
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://www.traceloop.com/openllmetry
  repository: https://github.com/traceloop/openllmetry
  documentation: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
